version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    # - funcorder        # current layout is logical.
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnil
    - predeclared
    - reassign
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
    - wsl_v5

  settings:
    cyclop:
      max-complexity: 30
      package-average: 0
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
    funlen:
      lines: -1
      statements: 65
    gocognit:
      min-complexity: 40
    goconst:
      min-occurrences: 5
    govet:
      enable-all: true
      disable:
        - fieldalignment

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

    rules:
      # The example app has some fmt.Println statements, it's fine.
      - path: examples/
        linters:
          - forbidigo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/kuzmik/libconfig
  exclusions:
    generated: lax

run:
  tests: false
